#ifndef _SCENE_COLOR_H_
#define _SCENE_COLOR_H_


#define OSD_WINDOW_BUTTON0_UP       0
#define OSD_BLOCK_BUTTON0_UP_B4 0
#define OSD_BLOCK_BUTTON0_UP_B0_0 1
#define OSD_BLOCK_BUTTON0_UP_B1_0 2
#define OSD_BLOCK_BUTTON0_UP_B2_0 3
#define OSD_BLOCK_BUTTON0_UP_B3_0 4
#define OSD_WINDOW_BUTTON0_DOWN     1
#define OSD_BLOCK_BUTTON0_DOWN_B4 0
#define OSD_BLOCK_BUTTON0_DOWN_B0_0 1
#define OSD_BLOCK_BUTTON0_DOWN_B0_0 2
#define OSD_BLOCK_BUTTON0_DOWN_B0_0 3
#define OSD_BLOCK_BUTTON0_DOWN_B0_0 4
#define OSD_WINDOW_BUTTON1          2
#define OSD_BLOCK_BUTTON1_B4 0
#define OSD_BLOCK_BUTTON1_B0_0 1
#define OSD_BLOCK_BUTTON1_B1_0 2
#define OSD_BLOCK_BUTTON1_B2_0 3
#define OSD_BLOCK_BUTTON1_B3_0 4
#define OSD_WINDOW_BUTTON2          3
#define OSD_BLOCK_BUTTON2_B4 0
#define OSD_BLOCK_BUTTON2_B0_0 1
#define OSD_BLOCK_BUTTON2_B1_0 2
#define OSD_BLOCK_BUTTON2_B2_0 3
#define OSD_BLOCK_BUTTON2_B3_0 4
#define OSD_WINDOW_BUTTON3          4
#define OSD_BLOCK_BUTTON3_B4 0
#define OSD_BLOCK_BUTTON3_B0_0 1
#define OSD_BLOCK_BUTTON3_B1_0 2
#define OSD_BLOCK_BUTTON3_B2_0 3
#define OSD_BLOCK_BUTTON3_B3_0 4
#define OSD_WINDOW_BUTTON           5
#define OSD_BLOCK_BUTTON_B4 0
#define OSD_BLOCK_BUTTON_B0_0 1
#define OSD_BLOCK_BUTTON_B1_0 2
#define OSD_BLOCK_BUTTON_B2_0 3
#define OSD_BLOCK_BUTTON_B3_0 4

#endif