#ifndef _SCENE_FORM_H_
#define _SCENE_FORM_H_


#define OSD_WINDOW_WINDOW0          0
#define OSD_BLOCK_WINDOW0_ 0
#define OSD_BLOCK_WINDOW0_ 1
#define OSD_BLOCK_WINDOW0_R_0 2
#define OSD_BLOCK_WINDOW0_R_1 3
#define OSD_BLOCK_WINDOW0_R_2 4
#define OSD_BLOCK_WINDOW0_R_3 5
#define OSD_BLOCK_WINDOW0_R_4 6
#define OSD_WINDOW_WINDOW1          1
#define OSD_BLOCK_WINDOW1_ 0
#define OSD_BLOCK_WINDOW1_ 1
#define OSD_BLOCK_WINDOW1_R_0 2
#define OSD_BLOCK_WINDOW1_R_1 3
#define OSD_BLOCK_WINDOW1_R_2 4
#define OSD_BLOCK_WINDOW1_R_3 5
#define OSD_BLOCK_WINDOW1_R_4 6
#define OSD_WINDOW_WINDOW2          2
#define OSD_BLOCK_WINDOW2_ 0
#define OSD_BLOCK_WINDOW2_ 1
#define OSD_BLOCK_WINDOW2_R_0 2
#define OSD_BLOCK_WINDOW2_R_1 3
#define OSD_BLOCK_WINDOW2_R_2 4
#define OSD_BLOCK_WINDOW2_R_3 5
#define OSD_BLOCK_WINDOW2_R_4 6

#endif