#ifndef _SCENE_HELLO_H_
#define _SCENE_HELLO_H_


#define OSD_WINDOW_WINDOW_RECT      0
#define OSD_BLOCK_WINDOW_RECT_B0 0
#define OSD_BLOCK_WINDOW_RECT_B1 1
#define OSD_BLOCK_WINDOW_RECT_B2 2
#define OSD_BLOCK_WINDOW_RECT_B3 3

#endif