#ifndef _SCENE_LABEL2_H_
#define _SCENE_LABEL2_H_


#define OSD_WINDOW_WINDOW_RECT      0
#define OSD_BLOCK_WINDOW_RECT_R 0
#define OSD_BLOCK_WINDOW_RECT_L_0 1
#define OSD_BLOCK_WINDOW_RECT_L_1 2
#define OSD_BLOCK_WINDOW_RECT_L_2 3
#define OSD_BLOCK_WINDOW_RECT_L_3 4
#define OSD_BLOCK_WINDOW_RECT_L_4 5

#endif