#ifndef _SCENE_PROGRESSBAR_H_
#define _SCENE_PROGRESSBAR_H_


#define OSD_WINDOW_PROGRESS         0
#define OSD_BLOCK_PROGRESS_B0 0
#define OSD_BLOCK_PROGRESS_B0 1
#define OSD_BLOCK_PROGRESS_B0_0 2
#define OSD_BLOCK_PROGRESS_B0_0 3
#define OSD_BLOCK_PROGRESS_B0_0 4
#define OSD_WINDOW_PROGRESS2        1
#define OSD_BLOCK_PROGRESS2_B0 0

#endif