#ifndef _SCENE_RECT_H_
#define _SCENE_RECT_H_


#define OSD_WINDOW_WINDOW_RECT      0
#define OSD_BLOCK_WINDOW_RECT_B0 0
#define OSD_BLOCK_WINDOW_RECT_B1 1
#define OSD_BLOCK_WINDOW_RECT_B1 2
#define OSD_BLOCK_WINDOW_RECT_B1 3
#define OSD_BLOCK_WINDOW_RECT_B1 4
#define OSD_BLOCK_WINDOW_RECT_B1 5
#define OSD_BLOCK_WINDOW_RECT_B1 6

#endif