Scene:
  width:  800
  height: 600
  default_palette: palette0
  default_font: mono_16
  default_font_size: 24
  title: sysset

  Defines:
    transparant: 0
    black: 1
    white: 2
    input_bg_color: 10
    input_bg_hl_color: 11
    input_text_color: 1
    input_text_hl_color: 12
    height: '+48'
    font_height: '+48'

  Fonts:
    - Preload:
        id: preload1
        font: mono_16
        size: 24
        text: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890abcdefghijklmnopqrstuvwxyz'

  Includes:
    - Include:
        file: common.yaml

  Palettes:
    - Palette:
        id: palette0
        colors: [0x000000, 0x000000, 0xFFFFFF, 0xFF0000, 0xFF00FF,
                 0x7171C6, 0x808080, 0xD0D0D0, 0x8FBC8F, 0xEEE8CD,
                 0x909090, 0x104E8B, 0xCDCD00, 0x9191E6]

  Ingredients:
    ####################################
    ###           left               ###
    ####################################
    - Bitmap:
        id: left_top_left
        bitmaps: 'images/left_top_left.bmp'

    - Bitmap:
        id: left_top_right
        bitmaps: 'images/left_top_right.bmp'

    - Bitmap:
        id: left_top_tile
        bitmaps: 'images/left_top_tile.bmp'
        tiled: true
        width: 262

    - Bitmap:
        id: icon_photo
        bitmaps: 'images/icon_photo.bmp'
        transparent_color: 0xFF00FF

    - Rectangle:
        id: rect_left_normal
        border_weight: 1
        border_color: 2
        bgcolor: [6, 7]
        height: 75
        gradient_mode: CORNER_TO_CENTER

    - Rectangle:
        id: rect_left_selected
        border_weight: 1
        border_color: 2
        bgcolor: [5, 13]
        height: 70
        gradient_mode: CORNER_TO_CENTER

    - Rectangle:
        id: rect_left_focused
        border_weight: 3
        border_color: 2
        bgcolor: [5, 13]
        height: 70
        gradient_mode: CORNER_TO_CENTER

    - Label:
        id: label_menu_picture
        text: 'Picture'
        width: 280
        height: 75
        color: [1, 2, 2]
        background: [rect_left_normal, rect_left_selected, rect_left_focused]
        align: CENTER
        state: 0
        mutable: True

    - Label:
        id: label_menu_sound
        text: 'Sound'
        color: [1, 2, 2]
        width: 280
        height: 75
        background: [rect_left_normal, rect_left_selected, rect_left_focused]
        align: CENTER
        state: 0
        mutable: True

    - Label:
        id: label_menu_channel
        text: 'Channel'
        color: [1, 2, 2]
        width: 280
        height: 75
        background: [rect_left_normal, rect_left_selected, rect_left_focused]
        align: CENTER
        state: 0
        mutable: True

    - Label:
        id: label_menu_feature
        text: 'Feature'
        color: [1, 2, 2]
        width: 280
        height: 75
        background: [rect_left_normal, rect_left_selected, rect_left_focused]
        align: CENTER
        state: 0
        mutable: True

    - Label:
        id: label_menu_setup
        text: 'Setup'
        color: [1, 2, 2]
        width: 280
        height: 75
        background: [rect_left_normal, rect_left_selected, rect_left_focused]
        align: CENTER
        state: 0
        mutable: True

    ####################################
    ###           top                ###
    ####################################
    - Bitmap:
        id: title_tile
        bitmaps: 'images/title_tile.bmp'
        tiled: true
        width: 410

    - Bitmap:
        id: title_left
        bitmaps: 'images/title_left.bmp'

    - Bitmap:
        id: title_right
        bitmaps: 'images/title_right.bmp'

    - Label:
        id: label_title
        text: ['Picture', 'Sound', 'Channel', 'Feature', 'Setup']
        mutable: True
        color: 4

    ####################################
    ###           bottom             ###
    ####################################
    - Bitmap:
        id: left_bottom
        bitmaps: 'images/left_bottom.bmp'
        width: 50

    - Bitmap:
        id: bottom
        bitmaps: 'images/bottom.bmp'
        tiled: True
        width: 750

    - Bitmap:
        id: move
        bitmaps: 'images/move.bmp'
        transparent_color: 0xFF00FF

    - Bitmap:
        id: enter
        bitmaps: 'images/enter.bmp'
        transparent_color: 0xFF00FF

    - Bitmap:
        id: exit
        bitmaps: 'images/exit.bmp'
        transparent_color: 0xFF00FF

    - Bitmap:
        id: menu
        bitmaps: 'images/menu.bmp'
        transparent_color: 0xFF00FF

    - Label:
        id: label_move
        text: 'Move'
        color: $white

    - Label:
        id: label_enter
        text: 'Enter'
        color: $white

    - Label:
        id: label_exit
        text: 'Exit'
        color: $white

    - Label:
        id: label_return
        text: 'Return'
        color: $white

    ####################################
    ###           center             ###
    ####################################
    - Rectangle:
        id: rect_center_bar_1
        bgcolor: 8
        height: 48

    - Rectangle:
        id: rect_center_bar_2
        bgcolor: 9
        height: 48

    - Bitmap:
        id: page_up
        bitmaps: 'images/page_up.bmp'
        transparent_color: 0xFF00FF

    - Bitmap:
        id: page_down
        bitmaps: 'images/page_down.bmp'
        transparent_color: 0xFF00FF

    - Bitmap:
        id: left
        bitmaps: 'images/left.bmp'
        transparent_color: 0xFE02FE

    - Bitmap:
        id: right
        bitmaps: 'images/right.bmp'
        transparent_color: 0xFE02FE

    - Label:
        id: label_picture_mode
        text: 'Picture Mode'
        color: $black
        width: 250
        align: CENTER

    - Label:
        id: label_brightness
        text: 'Brightness'
        color: $black
        width: 250
        align: CENTER

    - Label:
        id: label_contrast
        text: 'Contrast'
        color: $black
        width: 250
        align: CENTER

    - Label:
        id: label_sharpness
        text: 'Sharpness'
        color: $black
        width: 250
        align: CENTER

    - Label:
        id: label_color
        text: 'Colour'
        color: $black
        width: 250
        align: CENTER

    - Label:
        id: label_tint
        text: 'Tint'
        color: $black
        width: 250
        align: CENTER

    - Label:
        id: label_color_temp
        text: 'Colour Temperature'
        color: $black
        width: 250
        align: CENTER

    - Label:
        id: label_aspect_ratio
        text: 'Aspect Ratio'
        color: $black
        width: 250
        align: CENTER


    - Rectangle:
        id: rect_center_normal
        bgcolor: $input_bg_color

    - Rectangle:
        id: rect_center_selected
        bgcolor: $input_bg_hl_color

    - Rectangle:
        id: rect_center_focused
        bgcolor: $input_bg_hl_color
        border_weight: 4
        border_color: 2

    - Label:
        id: text_picture_mode
        text: ['Standard', 'Dynamic', 'Mild', 'User']
        width: 200
        height: 40
        mutable: True
        align: CENTER
        color: [$input_text_color, $input_text_hl_color, $input_text_hl_color]
        background: [rect_center_normal, rect_center_selected, rect_center_focused]
        state: 0


    - Label:
        id: text_brightness
        text: '50'
        width: 200
        height: 40
        mutable: True
        align: CENTER
        color: [$input_text_color, $input_text_hl_color, $input_text_hl_color]
        background: [rect_center_normal, rect_center_selected, rect_center_focused]
        state: 0

    - Label:
        id: text_contrast
        text: '50'
        width: 200
        height: 40
        mutable: True
        align: CENTER
        color: [$input_text_color, $input_text_hl_color, $input_text_hl_color]
        background: [rect_center_normal, rect_center_selected, rect_center_focused]
        state: 0

    - Label:
        id: text_sharpness
        text: '50'
        width: 200
        height: 40
        mutable: True
        align: CENTER
        color: [$input_text_color, $input_text_hl_color, $input_text_hl_color]
        background: [rect_center_normal, rect_center_selected, rect_center_focused]
        state: 0

    - Label:
        id: text_color
        text: '50'
        width: 200
        height: 40
        mutable: True
        align: CENTER
        color: [$input_text_color, $input_text_hl_color, $input_text_hl_color]
        background: [rect_center_normal, rect_center_selected, rect_center_focused]
        state: 0

    - Label:
        id: text_tint
        text: '50'
        width: 200
        height: 40
        mutable: True
        align: CENTER
        color: [$input_text_color, $input_text_hl_color, $input_text_hl_color]
        background: [rect_center_normal, rect_center_selected, rect_center_focused]
        state: 0

    - Label:
        id: text_color_temp
        text: ['Standard', 'Cool', 'Warm']
        width: 200
        height: 40
        mutable: True
        align: CENTER
        color: [$input_text_color, $input_text_hl_color, $input_text_hl_color]
        background: [rect_center_normal, rect_center_selected, rect_center_focused]
        state: 0

    - Label:
        id: text_aspect_ratio
        text: '50'
        width: 200
        height: 40
        mutable: True
        align: CENTER
        color: [$input_text_color, $input_text_hl_color, $input_text_hl_color]
        background: [rect_center_normal, rect_center_selected, rect_center_focused]
        state: 0

  Windows:
    - Window:
        id: center
        x: 282
        y: 71
        width: 518
        height: 482
        blocks:
          - ['', rect_center_bar_1, 0, 0]
          - ['', rect_center_bar_2, 0, $height]
          - ['', rect_center_bar_1, 0, $height]
          - ['', rect_center_bar_2, 0, $height]
          - ['', rect_center_bar_1, 0, $height]
          - ['', rect_center_bar_2, 0, $height]
          - ['', rect_center_bar_1, 0, $height]
          - ['', rect_center_bar_2, 0, $height]
          - ['', rect_center_bar_1, 0, $height]
          - ['', rect_center_bar_2, 0, $height]

          - ['', label_picture_mode, 0, 60]
          - ['', label_brightness, 0,   $font_height]
          - ['', label_contrast, 0,   $font_height]
          - ['', label_sharpness, 0,   $font_height]
          - ['', label_color, 0,   $font_height]
          - ['', label_tint, 0,   $font_height]
          - ['', label_color_temp, 0,   $font_height]
          - ['', label_aspect_ratio, 0,   $font_height]

          - ['', text_picture_mode, 280, 52]
          - ['', text_brightness, 280, $font_height]
          - ['', text_contrast, 280, $font_height]
          - ['', text_sharpness, 280, $font_height]
          - ['', text_color, 280, $font_height]
          - ['', text_tint, 280, $font_height]
          - ['', text_color_temp, 280, $font_height]
          - ['', text_aspect_ratio, 280, $font_height]

          - ['', left, 260, 60]
          - ['', right, 485, 60]

          - ['', page_up, 300, 0]
          - ['', page_down, 300, 456]



    - Window:
        id: left
        x: 0
        y: 0
        width: 282
        height: 553
        blocks:
          - ['', left_top_left, 0, 0]
          - ['', left_top_tile, 10, 0]
          - ['', left_top_right, 271, 0]
          - ['', icon_photo, 90, 60]

          - ['', label_menu_picture, 0, 175]
          - ['', label_menu_sound, 0, '+75']
          - ['', label_menu_channel, 0, '+75']
          - ['', label_menu_feature, 0, '+75']
          - ['', label_menu_setup, 0, '+75']

    - Window:
        id: top
        x: 282
        y: 0
        width: 518
        height: 71
        blocks:
          - ['', title_left, 0, 0]
          - ['', title_tile, 73, 0]
          - ['', title_right, 483, 0]
          - ['', label_title, 250, 32]



    - Window:
        id: bottom
        x: 0
        y: 553
        width: 1.0
        height: 47
        blocks:
          - ['', left_bottom, 0, 0]
          - ['', bottom, 50, 0]
          - ['', move, '+50', 15]
          - ['', enter, '+170', 15]
          - ['', exit, '+170', 15]
          - ['', menu, '+170', 15]
          - ['', label_move, 170, 12]
          - ['', label_enter, '+170', 12]
          - ['', label_exit, '+170', 12]
          - ['', label_return, '+170', 12]

