#ifndef _SCENE_SYSTEM_SETTINGS_H_
#define _SCENE_SYSTEM_SETTINGS_H_

#define OSD_INGREDIENT_LABEL_TITLE      52
#define OSD_INGREDIENT_RECT_INPUT_PICTURE_MODE 175
#define OSD_INGREDIENT_RECT_INPUT_BRIGHTNESS 176
#define OSD_INGREDIENT_RECT_INPUT_CONTRAST 177
#define OSD_INGREDIENT_RECT_INPUT_SHARPNESS 178
#define OSD_INGREDIENT_RECT_INPUT_COLOR 179
#define OSD_INGREDIENT_RECT_INPUT_TINT  180
#define OSD_INGREDIENT_RECT_INPUT_COLOR_TEMP 181
#define OSD_INGREDIENT_RECT_INPUT_ASPECT_RATIO 182
#define OSD_INGREDIENT_TEXT_PICTURE_MODE 191
#define OSD_INGREDIENT_TEXT_BRIGHTNESS  194
#define OSD_INGREDIENT_TEXT_CONTRAST    197
#define OSD_INGREDIENT_TEXT_SHARPNESS   200
#define OSD_INGREDIENT_TEXT_COLOR       203
#define OSD_INGREDIENT_TEXT_TINT        206
#define OSD_INGREDIENT_TEXT_COLOR_TEMP  215
#define OSD_INGREDIENT_TEXT_ASPECT_RATIO 218

#define OSD_WINDOW_CENTER           0
#define OSD_WINDOW_LEFT             1
#define OSD_WINDOW_TOP              2
#define OSD_WINDOW_BOTTOM           3

#endif