#ifndef _SCENE_SYSTEM_SETTINGS_H_
#define _SCENE_SYSTEM_SETTINGS_H_

#define OSD_INGREDIENT_LABEL_MENU_PICTURE 14
#define OSD_INGREDIENT_LABEL_MENU_SOUND 20
#define OSD_INGREDIENT_LABEL_MENU_CHANNEL 28
#define OSD_INGREDIENT_LABEL_MENU_FEATURE 36
#define OSD_INGREDIENT_LABEL_MENU_SETUP 42
#define OSD_INGREDIENT_LABEL_TITLE      77
#define OSD_INGREDIENT_LEFT             111
#define OSD_INGREDIENT_RIGHT            112
#define OSD_INGREDIENT_TEXT_PICTURE_MODE 226
#define OSD_INGREDIENT_TEXT_BRIGHTNESS  229
#define OSD_INGREDIENT_TEXT_CONTRAST    232
#define OSD_INGREDIENT_TEXT_SHARPNESS   235
#define OSD_INGREDIENT_TEXT_COLOR       238
#define OSD_INGREDIENT_TEXT_TINT        241
#define OSD_INGREDIENT_TEXT_COLOR_TEMP  258
#define OSD_INGREDIENT_TEXT_ASPECT_RATIO 266

#define OSD_WINDOW_PICTURE_MODE     0
#define OSD_BLOCK_PICTURE_MODE_LEFT_ARROW 169
#define OSD_BLOCK_PICTURE_MODE_RIGHT_ARROW 170
#define OSD_WINDOW_LEFT             1
#define OSD_WINDOW_TOP              2
#define OSD_WINDOW_BOTTOM           3

#endif