#ifndef _SCENE_SYSTEM_SETTINGS_H_
#define _SCENE_SYSTEM_SETTINGS_H_

#define OSD_INGREDIENT_LABEL_MENU_PICTURE 28
#define OSD_INGREDIENT_LABEL_MENU_SOUND 44
#define OSD_INGREDIENT_LABEL_MENU_CHANNEL 66
#define OSD_INGREDIENT_LABEL_MENU_FEATURE 88
#define OSD_INGREDIENT_LABEL_MENU_SETUP 104
#define OSD_INGREDIENT_LABEL_TITLE      139

#define OSD_WINDOW_CENTER           0
#define OSD_WINDOW_LEFT             1
#define OSD_WINDOW_TOP              2
#define OSD_WINDOW_BOTTOM           3

#endif